allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  workerd: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - workerd
packages:
  - .
